// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InAppNotification struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Title     string             `db:"title" json:"title"`
	Message   string             `db:"message" json:"message"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Notification struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ServiceID  uuid.UUID          `db:"service_id" json:"service_id"`
	UserID     string             `db:"user_id" json:"user_id"`
	Title      string             `db:"title" json:"title"`
	Message    string             `db:"message" json:"message"`
	Channels   []string           `db:"channels" json:"channels"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	Status     string             `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PushSubscription struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Channel   string             `db:"channel" json:"channel"`
	Endpoint  string             `db:"endpoint" json:"endpoint"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Service struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	ApiKey      string             `db:"api_key" json:"api_key"`
	Description *string            `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UsersPreference struct {
	UserID     string `db:"user_id" json:"user_id"`
	EmailOptIn bool   `db:"email_opt_in" json:"email_opt_in"`
	SmsOptIn   bool   `db:"sms_opt_in" json:"sms_opt_in"`
}
