// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultEnvironmentByOrganization = `-- name: ClearDefaultEnvironmentByOrganization :exec
UPDATE environments
SET is_default = false, updated_at = $2
WHERE organization_id = $1 AND is_default = true
`

type ClearDefaultEnvironmentByOrganizationParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ClearDefaultEnvironmentByOrganization(ctx context.Context, arg ClearDefaultEnvironmentByOrganizationParams) error {
	_, err := q.db.Exec(ctx, clearDefaultEnvironmentByOrganization, arg.OrganizationID, arg.UpdatedAt)
	return err
}

const clearIntegrationPrimaryByChannel = `-- name: ClearIntegrationPrimaryByChannel :exec
UPDATE integrations
SET is_primary = false, updated_at = now()
WHERE environment_id = $1 AND channel = $2 AND is_primary = true
`

type ClearIntegrationPrimaryByChannelParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Channel       string    `db:"channel" json:"channel"`
}

func (q *Queries) ClearIntegrationPrimaryByChannel(ctx context.Context, arg ClearIntegrationPrimaryByChannelParams) error {
	_, err := q.db.Exec(ctx, clearIntegrationPrimaryByChannel, arg.EnvironmentID, arg.Channel)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (
	id,
	environment_id,
	name,
	key_prefix,
	key_hash,
	scopes,
	status,
	expires_at,
	rotated_from,
	created_at,
	updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAPIKeyParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EnvironmentID uuid.UUID          `db:"environment_id" json:"environment_id"`
	Name          string             `db:"name" json:"name"`
	KeyPrefix     string             `db:"key_prefix" json:"key_prefix"`
	KeyHash       string             `db:"key_hash" json:"key_hash"`
	Scopes        []byte             `db:"scopes" json:"scopes"`
	Status        string             `db:"status" json:"status"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RotatedFrom   pgtype.UUID        `db:"rotated_from" json:"rotated_from"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.Status,
		arg.ExpiresAt,
		arg.RotatedFrom,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :exec
INSERT INTO auth_identities (
	id,
	user_id,
	provider,
	provider_user_id,
	email,
	created_at,
	updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuthIdentityParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderUserID string             `db:"provider_user_id" json:"provider_user_id"`
	Email          string             `db:"email" json:"email"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, organization_id, name, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, is_default, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Name           string             `db:"name" json:"name"`
	IsDefault      bool               `db:"is_default" json:"is_default"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEnvironmentWithOrg = `-- name: CreateEnvironmentWithOrg :one
INSERT INTO environments (id, organization_id, name, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, is_default, created_at, updated_at
`

type CreateEnvironmentWithOrgParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Name           string             `db:"name" json:"name"`
	IsDefault      bool               `db:"is_default" json:"is_default"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateEnvironmentWithOrg(ctx context.Context, arg CreateEnvironmentWithOrgParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironmentWithOrg,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (id, environment_id, name, channel, credentials, config, is_active, is_primary)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
`

type CreateIntegrationParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Channel       string    `db:"channel" json:"channel"`
	Credentials   []byte    `db:"credentials" json:"credentials"`
	Config        []byte    `db:"config" json:"config"`
	IsActive      bool      `db:"is_active" json:"is_active"`
	IsPrimary     bool      `db:"is_primary" json:"is_primary"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Channel,
		arg.Credentials,
		arg.Config,
		arg.IsActive,
		arg.IsPrimary,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Credentials,
		&i.Config,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :exec
INSERT INTO organization_members (id, organization_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrganizationMemberParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Role           string             `db:"role" json:"role"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, createOrganizationMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (
	id,
	environment_id,
	name,
	email,
	phone,
	push_token,
	channels,
	status,
	tags,
	metadata,
	preferences
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, environment_id, name, email, phone, push_token, channels, status, tags, preferences, subscription_date, last_notification_date, metadata, deleted_at, created_at, updated_at
`

type CreateSubscriberParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Email         *string   `db:"email" json:"email"`
	Phone         *string   `db:"phone" json:"phone"`
	PushToken     *string   `db:"push_token" json:"push_token"`
	Channels      []string  `db:"channels" json:"channels"`
	Status        []byte    `db:"status" json:"status"`
	Tags          []string  `db:"tags" json:"tags"`
	Metadata      []byte    `db:"metadata" json:"metadata"`
	Preferences   []byte    `db:"preferences" json:"preferences"`
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PushToken,
		arg.Channels,
		arg.Status,
		arg.Tags,
		arg.Metadata,
		arg.Preferences,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PushToken,
		&i.Channels,
		&i.Status,
		&i.Tags,
		&i.Preferences,
		&i.SubscriptionDate,
		&i.LastNotificationDate,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (id, environment_id, name, channel, subject, body)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, environment_id, name, channel, subject, body, version, is_active, created_at, updated_at
`

type CreateTemplateParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Channel       string    `db:"channel" json:"channel"`
	Subject       *string   `db:"subject" json:"subject"`
	Body          string    `db:"body" json:"body"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Channel,
		arg.Subject,
		arg.Body,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
	id,
	email,
	password_hash,
	first_name,
	last_name,
	email_verified_at,
	onboarding_completed_at,
	created_at,
	updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	Email                 string             `db:"email" json:"email"`
	PasswordHash          string             `db:"password_hash" json:"password_hash"`
	FirstName             string             `db:"first_name" json:"first_name"`
	LastName              string             `db:"last_name" json:"last_name"`
	EmailVerifiedAt       pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	OnboardingCompletedAt pgtype.Timestamptz `db:"onboarding_completed_at" json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.EmailVerifiedAt,
		arg.OnboardingCompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, environment_id, url, secret, events, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, true, $6, $7)
RETURNING id, environment_id, url, secret, events, is_active, created_at, updated_at
`

type CreateWebhookParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EnvironmentID uuid.UUID          `db:"environment_id" json:"environment_id"`
	Url           string             `db:"url" json:"url"`
	Secret        string             `db:"secret" json:"secret"`
	Events        []string           `db:"events" json:"events"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.EnvironmentID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (
	id,
	environment_id,
	key,
	name,
	description,
	channels,
	template_ids,
	is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7, true)
RETURNING id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Key           string    `db:"key" json:"key"`
	Name          string    `db:"name" json:"name"`
	Description   *string   `db:"description" json:"description"`
	Channels      []string  `db:"channels" json:"channels"`
	TemplateIds   []byte    `db:"template_ids" json:"template_ids"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.ID,
		arg.EnvironmentID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Channels,
		arg.TemplateIds,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Channels,
		&i.TemplateIds,
		&i.IsActive,
		&i.Status,
		&i.Version,
		&i.TriggerEvent,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowDefinition = `-- name: CreateWorkflowDefinition :one
INSERT INTO workflows (
	id,
	environment_id,
	key,
	name,
	description,
	status,
	version,
	trigger_event,
	definition_json,
	is_active
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	true
)
RETURNING id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at
`

type CreateWorkflowDefinitionParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EnvironmentID  uuid.UUID `db:"environment_id" json:"environment_id"`
	Key            string    `db:"key" json:"key"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	Status         string    `db:"status" json:"status"`
	Version        int32     `db:"version" json:"version"`
	TriggerEvent   *string   `db:"trigger_event" json:"trigger_event"`
	DefinitionJson []byte    `db:"definition_json" json:"definition_json"`
}

func (q *Queries) CreateWorkflowDefinition(ctx context.Context, arg CreateWorkflowDefinitionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflowDefinition,
		arg.ID,
		arg.EnvironmentID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Version,
		arg.TriggerEvent,
		arg.DefinitionJson,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Channels,
		&i.TemplateIds,
		&i.IsActive,
		&i.Status,
		&i.Version,
		&i.TriggerEvent,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowExecution = `-- name: CreateWorkflowExecution :one
INSERT INTO workflow_executions (
	id,
	workflow_id,
	environment_id,
	subscriber_id,
	status,
	current_step_id,
	trigger_payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workflow_id, environment_id, subscriber_id, status, current_step_id, trigger_payload, started_at, completed_at, failed_at, created_at, updated_at
`

type CreateWorkflowExecutionParams struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	WorkflowID     uuid.UUID   `db:"workflow_id" json:"workflow_id"`
	EnvironmentID  uuid.UUID   `db:"environment_id" json:"environment_id"`
	SubscriberID   pgtype.UUID `db:"subscriber_id" json:"subscriber_id"`
	Status         string      `db:"status" json:"status"`
	CurrentStepID  *string     `db:"current_step_id" json:"current_step_id"`
	TriggerPayload []byte      `db:"trigger_payload" json:"trigger_payload"`
}

func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, createWorkflowExecution,
		arg.ID,
		arg.WorkflowID,
		arg.EnvironmentID,
		arg.SubscriberID,
		arg.Status,
		arg.CurrentStepID,
		arg.TriggerPayload,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.EnvironmentID,
		&i.SubscriberID,
		&i.Status,
		&i.CurrentStepID,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowStepExecution = `-- name: CreateWorkflowStepExecution :one
INSERT INTO workflow_step_executions (
	id,
	execution_id,
	step_id,
	step_type,
	status,
	attempts,
	input_json,
	output_json,
	error_json,
	started_at,
	completed_at,
	failed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, execution_id, step_id, step_type, status, attempts, input_json, output_json, error_json, started_at, completed_at, failed_at, created_at, updated_at
`

type CreateWorkflowStepExecutionParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	ExecutionID uuid.UUID          `db:"execution_id" json:"execution_id"`
	StepID      string             `db:"step_id" json:"step_id"`
	StepType    string             `db:"step_type" json:"step_type"`
	Status      string             `db:"status" json:"status"`
	Attempts    int32              `db:"attempts" json:"attempts"`
	InputJson   []byte             `db:"input_json" json:"input_json"`
	OutputJson  []byte             `db:"output_json" json:"output_json"`
	ErrorJson   []byte             `db:"error_json" json:"error_json"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	FailedAt    pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
}

func (q *Queries) CreateWorkflowStepExecution(ctx context.Context, arg CreateWorkflowStepExecutionParams) (WorkflowStepExecution, error) {
	row := q.db.QueryRow(ctx, createWorkflowStepExecution,
		arg.ID,
		arg.ExecutionID,
		arg.StepID,
		arg.StepType,
		arg.Status,
		arg.Attempts,
		arg.InputJson,
		arg.OutputJson,
		arg.ErrorJson,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
	)
	var i WorkflowStepExecution
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.StepID,
		&i.StepType,
		&i.Status,
		&i.Attempts,
		&i.InputJson,
		&i.OutputJson,
		&i.ErrorJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dashboardActiveIntegrationCount = `-- name: DashboardActiveIntegrationCount :one
SELECT COUNT(*)::bigint AS count
FROM integrations
WHERE environment_id = $1 AND is_active = true
`

func (q *Queries) DashboardActiveIntegrationCount(ctx context.Context, environmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardActiveIntegrationCount, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardActiveIntegrations = `-- name: DashboardActiveIntegrations :many
SELECT name, channel
FROM integrations
WHERE environment_id = $1 AND is_active = true
ORDER BY name
`

type DashboardActiveIntegrationsRow struct {
	Name    string `db:"name" json:"name"`
	Channel string `db:"channel" json:"channel"`
}

func (q *Queries) DashboardActiveIntegrations(ctx context.Context, environmentID uuid.UUID) ([]DashboardActiveIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, dashboardActiveIntegrations, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardActiveIntegrationsRow{}
	for rows.Next() {
		var i DashboardActiveIntegrationsRow
		if err := rows.Scan(&i.Name, &i.Channel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardChannelBreakdown = `-- name: DashboardChannelBreakdown :many
SELECT da.channel, COUNT(*)::bigint AS count
FROM delivery_attempts da
JOIN notifications n ON n.id = da.notification_id
WHERE n.environment_id = $1 AND n.is_test = false
GROUP BY da.channel
`

type DashboardChannelBreakdownRow struct {
	Channel string `db:"channel" json:"channel"`
	Count   int64  `db:"count" json:"count"`
}

func (q *Queries) DashboardChannelBreakdown(ctx context.Context, environmentID pgtype.UUID) ([]DashboardChannelBreakdownRow, error) {
	rows, err := q.db.Query(ctx, dashboardChannelBreakdown, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardChannelBreakdownRow{}
	for rows.Next() {
		var i DashboardChannelBreakdownRow
		if err := rows.Scan(&i.Channel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardDailyActivity = `-- name: DashboardDailyActivity :many
SELECT
    DATE(created_at)::date AS day,
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE status IN ('sent', 'partial_failed'))::bigint AS delivered
FROM notifications
WHERE environment_id = $1 AND created_at >= $2 AND is_test = false
GROUP BY DATE(created_at)
ORDER BY day
`

type DashboardDailyActivityParams struct {
	EnvironmentID pgtype.UUID        `db:"environment_id" json:"environment_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DashboardDailyActivityRow struct {
	Day       pgtype.Date `db:"day" json:"day"`
	Total     int64       `db:"total" json:"total"`
	Delivered int64       `db:"delivered" json:"delivered"`
}

func (q *Queries) DashboardDailyActivity(ctx context.Context, arg DashboardDailyActivityParams) ([]DashboardDailyActivityRow, error) {
	rows, err := q.db.Query(ctx, dashboardDailyActivity, arg.EnvironmentID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardDailyActivityRow{}
	for rows.Next() {
		var i DashboardDailyActivityRow
		if err := rows.Scan(&i.Day, &i.Total, &i.Delivered); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardNotificationCount = `-- name: DashboardNotificationCount :one
SELECT COUNT(*)::bigint AS count
FROM notifications
WHERE environment_id = $1 AND is_test = false
`

func (q *Queries) DashboardNotificationCount(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardNotificationCount, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardNotificationStats = `-- name: DashboardNotificationStats :many
SELECT status, COUNT(*)::bigint AS count
FROM notifications
WHERE environment_id = $1 AND is_test = false
GROUP BY status
`

type DashboardNotificationStatsRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) DashboardNotificationStats(ctx context.Context, environmentID pgtype.UUID) ([]DashboardNotificationStatsRow, error) {
	rows, err := q.db.Query(ctx, dashboardNotificationStats, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardNotificationStatsRow{}
	for rows.Next() {
		var i DashboardNotificationStatsRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentNotifications = `-- name: DashboardRecentNotifications :many
SELECT id, title, message, channels, status, created_at
FROM notifications
WHERE environment_id = $1 AND is_test = false
ORDER BY created_at DESC
LIMIT $2
`

type DashboardRecentNotificationsParams struct {
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	Limit         int32       `db:"limit" json:"limit"`
}

type DashboardRecentNotificationsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Message   string             `db:"message" json:"message"`
	Channels  []string           `db:"channels" json:"channels"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) DashboardRecentNotifications(ctx context.Context, arg DashboardRecentNotificationsParams) ([]DashboardRecentNotificationsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentNotifications, arg.EnvironmentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentNotificationsRow{}
	for rows.Next() {
		var i DashboardRecentNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Channels,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSubscriberCount = `-- name: DashboardSubscriberCount :one
SELECT COUNT(*)::bigint AS count
FROM subscribers
WHERE environment_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DashboardSubscriberCount(ctx context.Context, environmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardSubscriberCount, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardWorkflowCount = `-- name: DashboardWorkflowCount :one
SELECT COUNT(*)::bigint AS count
FROM workflows
WHERE environment_id = $1 AND status <> 'archived'
`

func (q *Queries) DashboardWorkflowCount(ctx context.Context, environmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardWorkflowCount, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmailVerificationByUserID = `-- name: DeleteEmailVerificationByUserID :exec
DELETE FROM email_verifications
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationByUserID, userID)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations
WHERE id = $1 AND environment_id = $2
`

type DeleteIntegrationParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteIntegration, arg.ID, arg.EnvironmentID)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
UPDATE subscribers
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND environment_id = $2 AND deleted_at IS NULL
`

type DeleteSubscriberParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) DeleteSubscriber(ctx context.Context, arg DeleteSubscriberParams) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, arg.ID, arg.EnvironmentID)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
UPDATE templates
SET is_active = false, updated_at = now()
WHERE id = $1 AND environment_id = $2
`

type DeleteTemplateParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.EnvironmentID)
	return err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
UPDATE webhooks
SET is_active = false, updated_at = now()
WHERE id = $1 AND environment_id = $2
`

type DeleteWebhookParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.EnvironmentID)
	return err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
UPDATE workflows
SET is_active = false,
	status = 'archived',
	updated_at = now()
WHERE id = $1 AND environment_id = $2
`

type DeleteWorkflowParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, arg.ID, arg.EnvironmentID)
	return err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, environment_id, name, key_prefix, key_hash, scopes, status, last_used_at, expires_at, revoked_at, rotated_from, created_at, updated_at
FROM api_keys
WHERE key_prefix = $1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RotatedFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveEnvironmentIntegrationsByChannel = `-- name: GetActiveEnvironmentIntegrationsByChannel :many
SELECT id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
FROM integrations
WHERE environment_id = $1 AND channel = $2 AND is_active = true
ORDER BY is_primary DESC, created_at ASC
`

type GetActiveEnvironmentIntegrationsByChannelParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Channel       string    `db:"channel" json:"channel"`
}

func (q *Queries) GetActiveEnvironmentIntegrationsByChannel(ctx context.Context, arg GetActiveEnvironmentIntegrationsByChannelParams) ([]Integration, error) {
	rows, err := q.db.Query(ctx, getActiveEnvironmentIntegrationsByChannel, arg.EnvironmentID, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Channel,
			&i.Credentials,
			&i.Config,
			&i.IsActive,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveWorkflowsByTriggerEvent = `-- name: GetActiveWorkflowsByTriggerEvent :many
SELECT id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at FROM workflows
WHERE environment_id = $1
	AND trigger_event = $2
	AND status = 'active'
ORDER BY updated_at DESC
`

type GetActiveWorkflowsByTriggerEventParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	TriggerEvent  *string   `db:"trigger_event" json:"trigger_event"`
}

func (q *Queries) GetActiveWorkflowsByTriggerEvent(ctx context.Context, arg GetActiveWorkflowsByTriggerEventParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, getActiveWorkflowsByTriggerEvent, arg.EnvironmentID, arg.TriggerEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Channels,
			&i.TemplateIds,
			&i.IsActive,
			&i.Status,
			&i.Version,
			&i.TriggerEvent,
			&i.DefinitionJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthIdentityByProviderUserID = `-- name: GetAuthIdentityByProviderUserID :one
SELECT id, user_id, provider, provider_user_id, email, created_at, updated_at
FROM auth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetAuthIdentityByProviderUserIDParams struct {
	Provider       string `db:"provider" json:"provider"`
	ProviderUserID string `db:"provider_user_id" json:"provider_user_id"`
}

func (q *Queries) GetAuthIdentityByProviderUserID(ctx context.Context, arg GetAuthIdentityByProviderUserIDParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityByProviderUserID, arg.Provider, arg.ProviderUserID)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultEnvironmentByOrganization = `-- name: GetDefaultEnvironmentByOrganization :one
SELECT id, organization_id, name, is_default, created_at, updated_at
FROM environments
WHERE organization_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultEnvironmentByOrganization(ctx context.Context, organizationID uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getDefaultEnvironmentByOrganization, organizationID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailVerificationByUserID = `-- name: GetEmailVerificationByUserID :one
SELECT user_id, code_hash, expires_at, consumed_at, created_at, updated_at
FROM email_verifications
WHERE user_id = $1
`

func (q *Queries) GetEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByUserID, userID)
	var i EmailVerification
	err := row.Scan(
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, organization_id, name, is_default, created_at, updated_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, organization_id, name, is_default, created_at, updated_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentNotificationByID = `-- name: GetEnvironmentNotificationByID :one
SELECT id, title, message, channels, recipient, metadata, status, environment_id, job_id, is_test, created_at, updated_at
FROM notifications
WHERE id = $1 AND environment_id = $2
`

type GetEnvironmentNotificationByIDParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
}

type GetEnvironmentNotificationByIDRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	Channels      []string           `db:"channels" json:"channels"`
	Recipient     []byte             `db:"recipient" json:"recipient"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Status        string             `db:"status" json:"status"`
	EnvironmentID pgtype.UUID        `db:"environment_id" json:"environment_id"`
	JobID         *string            `db:"job_id" json:"job_id"`
	IsTest        bool               `db:"is_test" json:"is_test"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetEnvironmentNotificationByID(ctx context.Context, arg GetEnvironmentNotificationByIDParams) (GetEnvironmentNotificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentNotificationByID, arg.ID, arg.EnvironmentID)
	var i GetEnvironmentNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Channels,
		&i.Recipient,
		&i.Metadata,
		&i.Status,
		&i.EnvironmentID,
		&i.JobID,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstOrganizationByUser = `-- name: GetFirstOrganizationByUser :one
SELECT o.id, o.name, o.created_at, o.updated_at
FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY o.created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstOrganizationByUser(ctx context.Context, userID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getFirstOrganizationByUser, userID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstOrganizationMembershipByUser = `-- name: GetFirstOrganizationMembershipByUser :one
SELECT id, organization_id, user_id, role, created_at
FROM organization_members
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstOrganizationMembershipByUser(ctx context.Context, userID uuid.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getFirstOrganizationMembershipByUser, userID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
FROM integrations
WHERE id = $1 AND environment_id = $2
`

type GetIntegrationByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetIntegrationByID(ctx context.Context, arg GetIntegrationByIDParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, arg.ID, arg.EnvironmentID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Credentials,
		&i.Config,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByJobID = `-- name: GetNotificationByJobID :one
SELECT id, title, message, channels, recipient, metadata, status, environment_id, job_id, is_test, created_at, updated_at
FROM notifications
WHERE job_id = $1
`

type GetNotificationByJobIDRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	Channels      []string           `db:"channels" json:"channels"`
	Recipient     []byte             `db:"recipient" json:"recipient"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Status        string             `db:"status" json:"status"`
	EnvironmentID pgtype.UUID        `db:"environment_id" json:"environment_id"`
	JobID         *string            `db:"job_id" json:"job_id"`
	IsTest        bool               `db:"is_test" json:"is_test"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNotificationByJobID(ctx context.Context, jobID *string) (GetNotificationByJobIDRow, error) {
	row := q.db.QueryRow(ctx, getNotificationByJobID, jobID)
	var i GetNotificationByJobIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Channels,
		&i.Recipient,
		&i.Metadata,
		&i.Status,
		&i.EnvironmentID,
		&i.JobID,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, created_at
FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationMembershipByUser = `-- name: GetOrganizationMembershipByUser :one
SELECT id, organization_id, user_id, role, created_at
FROM organization_members
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMembershipByUserParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetOrganizationMembershipByUser(ctx context.Context, arg GetOrganizationMembershipByUserParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipByUser, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, updated_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one
SELECT id, environment_id, name, email, phone, push_token, channels, status, tags, preferences, subscription_date, last_notification_date, metadata, deleted_at, created_at, updated_at FROM subscribers
WHERE id = $1 AND environment_id = $2 AND deleted_at IS NULL
`

type GetSubscriberByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetSubscriberByID(ctx context.Context, arg GetSubscriberByIDParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByID, arg.ID, arg.EnvironmentID)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PushToken,
		&i.Channels,
		&i.Status,
		&i.Tags,
		&i.Preferences,
		&i.SubscriptionDate,
		&i.LastNotificationDate,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, environment_id, name, channel, subject, body, version, is_active, created_at, updated_at FROM templates
WHERE id = $1 AND environment_id = $2
`

type GetTemplateByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID, arg.EnvironmentID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, environment_id, name, channel, subject, body, version, is_active, created_at, updated_at FROM templates
WHERE environment_id = $1 AND name = $2 AND channel = $3 AND is_active = true
ORDER BY version DESC
LIMIT 1
`

type GetTemplateByNameParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Channel       string    `db:"channel" json:"channel"`
}

func (q *Queries) GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, arg.EnvironmentID, arg.Name, arg.Channel)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, email_verified_at, onboarding_completed_at, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, email_verified_at, onboarding_completed_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, environment_id, url, secret, events, is_active, created_at, updated_at
FROM webhooks
WHERE id = $1 AND environment_id = $2
`

type GetWebhookByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetWebhookByID(ctx context.Context, arg GetWebhookByIDParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, arg.ID, arg.EnvironmentID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at FROM workflows
WHERE id = $1 AND environment_id = $2
`

type GetWorkflowByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetWorkflowByID(ctx context.Context, arg GetWorkflowByIDParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, arg.ID, arg.EnvironmentID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Channels,
		&i.TemplateIds,
		&i.IsActive,
		&i.Status,
		&i.Version,
		&i.TriggerEvent,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowDefinitionByID = `-- name: GetWorkflowDefinitionByID :one
SELECT id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at FROM workflows
WHERE id = $1 AND environment_id = $2
`

type GetWorkflowDefinitionByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetWorkflowDefinitionByID(ctx context.Context, arg GetWorkflowDefinitionByIDParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinitionByID, arg.ID, arg.EnvironmentID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Channels,
		&i.TemplateIds,
		&i.IsActive,
		&i.Status,
		&i.Version,
		&i.TriggerEvent,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowExecutionByID = `-- name: GetWorkflowExecutionByID :one
SELECT id, workflow_id, environment_id, subscriber_id, status, current_step_id, trigger_payload, started_at, completed_at, failed_at, created_at, updated_at FROM workflow_executions
WHERE id = $1 AND environment_id = $2
`

type GetWorkflowExecutionByIDParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) GetWorkflowExecutionByID(ctx context.Context, arg GetWorkflowExecutionByIDParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, getWorkflowExecutionByID, arg.ID, arg.EnvironmentID)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.EnvironmentID,
		&i.SubscriberID,
		&i.Status,
		&i.CurrentStepID,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowStepExecution = `-- name: GetWorkflowStepExecution :one
SELECT id, execution_id, step_id, step_type, status, attempts, input_json, output_json, error_json, started_at, completed_at, failed_at, created_at, updated_at FROM workflow_step_executions
WHERE execution_id = $1 AND step_id = $2
`

type GetWorkflowStepExecutionParams struct {
	ExecutionID uuid.UUID `db:"execution_id" json:"execution_id"`
	StepID      string    `db:"step_id" json:"step_id"`
}

func (q *Queries) GetWorkflowStepExecution(ctx context.Context, arg GetWorkflowStepExecutionParams) (WorkflowStepExecution, error) {
	row := q.db.QueryRow(ctx, getWorkflowStepExecution, arg.ExecutionID, arg.StepID)
	var i WorkflowStepExecution
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.StepID,
		&i.StepType,
		&i.Status,
		&i.Attempts,
		&i.InputJson,
		&i.OutputJson,
		&i.ErrorJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :exec
INSERT INTO delivery_attempts (id, notification_id, channel, destination, status, error_message, provider_message_id, attempted_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertDeliveryAttemptParams struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	NotificationID    uuid.UUID          `db:"notification_id" json:"notification_id"`
	Channel           string             `db:"channel" json:"channel"`
	Destination       string             `db:"destination" json:"destination"`
	Status            string             `db:"status" json:"status"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	ProviderMessageID *string            `db:"provider_message_id" json:"provider_message_id"`
	AttemptedAt       pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryAttempt,
		arg.ID,
		arg.NotificationID,
		arg.Channel,
		arg.Destination,
		arg.Status,
		arg.ErrorMessage,
		arg.ProviderMessageID,
		arg.AttemptedAt,
	)
	return err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec
INSERT INTO webhook_deliveries (id, webhook_id, event, payload, status, response_code, error_message, attempted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertWebhookDeliveryParams struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	WebhookID    uuid.UUID          `db:"webhook_id" json:"webhook_id"`
	Event        string             `db:"event" json:"event"`
	Payload      []byte             `db:"payload" json:"payload"`
	Status       string             `db:"status" json:"status"`
	ResponseCode *int32             `db:"response_code" json:"response_code"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	AttemptedAt  pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.WebhookID,
		arg.Event,
		arg.Payload,
		arg.Status,
		arg.ResponseCode,
		arg.ErrorMessage,
		arg.AttemptedAt,
	)
	return err
}

const listAPIKeysByEnvironment = `-- name: ListAPIKeysByEnvironment :many
SELECT id, environment_id, name, key_prefix, key_hash, scopes, status, last_used_at, expires_at, revoked_at, rotated_from, created_at, updated_at
FROM api_keys
WHERE environment_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Status,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RotatedFrom,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, environment_id, url, secret, events, is_active, created_at, updated_at
FROM webhooks
WHERE environment_id = $1 AND is_active = true AND $2::text = ANY(events)
`

type ListActiveWebhooksForEventParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Column2       string    `db:"column_2" json:"column_2"`
}

func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, arg ListActiveWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForEvent, arg.EnvironmentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryAttemptsByNotificationID = `-- name: ListDeliveryAttemptsByNotificationID :many
SELECT id, notification_id, channel, destination, status, error_message, provider_message_id, attempted_at
FROM delivery_attempts
WHERE notification_id = $1
ORDER BY attempted_at ASC
`

func (q *Queries) ListDeliveryAttemptsByNotificationID(ctx context.Context, notificationID uuid.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttemptsByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Destination,
			&i.Status,
			&i.ErrorMessage,
			&i.ProviderMessageID,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentNotifications = `-- name: ListEnvironmentNotifications :many
SELECT id, title, message, channels, recipient, metadata, status, environment_id, job_id, is_test, created_at, updated_at
FROM notifications
WHERE environment_id = $1
  AND ($2::bool OR is_test = false)
ORDER BY created_at DESC
`

type ListEnvironmentNotificationsParams struct {
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	Column2       bool        `db:"column_2" json:"column_2"`
}

type ListEnvironmentNotificationsRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	Channels      []string           `db:"channels" json:"channels"`
	Recipient     []byte             `db:"recipient" json:"recipient"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Status        string             `db:"status" json:"status"`
	EnvironmentID pgtype.UUID        `db:"environment_id" json:"environment_id"`
	JobID         *string            `db:"job_id" json:"job_id"`
	IsTest        bool               `db:"is_test" json:"is_test"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListEnvironmentNotifications(ctx context.Context, arg ListEnvironmentNotificationsParams) ([]ListEnvironmentNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentNotifications, arg.EnvironmentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentNotificationsRow{}
	for rows.Next() {
		var i ListEnvironmentNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Channels,
			&i.Recipient,
			&i.Metadata,
			&i.Status,
			&i.EnvironmentID,
			&i.JobID,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByOrganization = `-- name: ListEnvironmentsByOrganization :many
SELECT id, organization_id, name, is_default, created_at, updated_at
FROM environments
WHERE organization_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEnvironmentsByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
FROM integrations
WHERE environment_id = $1
ORDER BY channel, is_primary DESC, name
`

func (q *Queries) ListIntegrations(ctx context.Context, environmentID uuid.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Channel,
			&i.Credentials,
			&i.Config,
			&i.IsActive,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByChannel = `-- name: ListIntegrationsByChannel :many
SELECT id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
FROM integrations
WHERE environment_id = $1 AND channel = $2
ORDER BY is_primary DESC, created_at ASC
`

type ListIntegrationsByChannelParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Channel       string    `db:"channel" json:"channel"`
}

func (q *Queries) ListIntegrationsByChannel(ctx context.Context, arg ListIntegrationsByChannelParams) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByChannel, arg.EnvironmentID, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Channel,
			&i.Credentials,
			&i.Config,
			&i.IsActive,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByWorkflowID = `-- name: ListNotificationsByWorkflowID :many
SELECT id, title, message, channels, status, is_test, created_at, updated_at
FROM notifications
WHERE environment_id = $1 AND metadata @> $2::jsonb
ORDER BY created_at DESC
LIMIT $3
`

type ListNotificationsByWorkflowIDParams struct {
	EnvironmentID pgtype.UUID `db:"environment_id" json:"environment_id"`
	Column2       []byte      `db:"column_2" json:"column_2"`
	Limit         int32       `db:"limit" json:"limit"`
}

type ListNotificationsByWorkflowIDRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Message   string             `db:"message" json:"message"`
	Channels  []string           `db:"channels" json:"channels"`
	Status    string             `db:"status" json:"status"`
	IsTest    bool               `db:"is_test" json:"is_test"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListNotificationsByWorkflowID(ctx context.Context, arg ListNotificationsByWorkflowIDParams) ([]ListNotificationsByWorkflowIDRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsByWorkflowID, arg.EnvironmentID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsByWorkflowIDRow{}
	for rows.Next() {
		var i ListNotificationsByWorkflowIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Channels,
			&i.Status,
			&i.IsTest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT o.id, o.name, o.created_at, o.updated_at
FROM organizations o
JOIN organization_members om ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY o.created_at ASC
`

func (q *Queries) ListOrganizationsByUser(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribersByEnvironment = `-- name: ListSubscribersByEnvironment :many
SELECT id, environment_id, name, email, phone, push_token, channels, status, tags, preferences, subscription_date, last_notification_date, metadata, deleted_at, created_at, updated_at FROM subscribers
WHERE environment_id = $1 AND deleted_at IS NULL
ORDER BY subscription_date DESC
`

func (q *Queries) ListSubscribersByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listSubscribersByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PushToken,
			&i.Channels,
			&i.Status,
			&i.Tags,
			&i.Preferences,
			&i.SubscriptionDate,
			&i.LastNotificationDate,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, environment_id, name, channel, subject, body, version, is_active, created_at, updated_at FROM templates
WHERE environment_id = $1
ORDER BY name, channel
`

func (q *Queries) ListTemplates(ctx context.Context, environmentID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Channel,
			&i.Subject,
			&i.Body,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByEnvironment = `-- name: ListWebhooksByEnvironment :many
SELECT id, environment_id, url, secret, events, is_active, created_at, updated_at
FROM webhooks
WHERE environment_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowDefinitionsByEnvironment = `-- name: ListWorkflowDefinitionsByEnvironment :many
SELECT id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at FROM workflows
WHERE environment_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListWorkflowDefinitionsByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowDefinitionsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Channels,
			&i.TemplateIds,
			&i.IsActive,
			&i.Status,
			&i.Version,
			&i.TriggerEvent,
			&i.DefinitionJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutionsByEnvironment = `-- name: ListWorkflowExecutionsByEnvironment :many
SELECT id, workflow_id, environment_id, subscriber_id, status, current_step_id, trigger_payload, started_at, completed_at, failed_at, created_at, updated_at FROM workflow_executions
WHERE environment_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListWorkflowExecutionsByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflowExecutionsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowExecution{}
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.EnvironmentID,
			&i.SubscriberID,
			&i.Status,
			&i.CurrentStepID,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowExecutionsByWorkflow = `-- name: ListWorkflowExecutionsByWorkflow :many
SELECT id, workflow_id, environment_id, subscriber_id, status, current_step_id, trigger_payload, started_at, completed_at, failed_at, created_at, updated_at FROM workflow_executions
WHERE workflow_id = $1 AND environment_id = $2
ORDER BY started_at DESC
`

type ListWorkflowExecutionsByWorkflowParams struct {
	WorkflowID    uuid.UUID `db:"workflow_id" json:"workflow_id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
}

func (q *Queries) ListWorkflowExecutionsByWorkflow(ctx context.Context, arg ListWorkflowExecutionsByWorkflowParams) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflowExecutionsByWorkflow, arg.WorkflowID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowExecution{}
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.EnvironmentID,
			&i.SubscriberID,
			&i.Status,
			&i.CurrentStepID,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepExecutionsByExecution = `-- name: ListWorkflowStepExecutionsByExecution :many
SELECT id, execution_id, step_id, step_type, status, attempts, input_json, output_json, error_json, started_at, completed_at, failed_at, created_at, updated_at FROM workflow_step_executions
WHERE execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWorkflowStepExecutionsByExecution(ctx context.Context, executionID uuid.UUID) ([]WorkflowStepExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepExecutionsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowStepExecution{}
	for rows.Next() {
		var i WorkflowStepExecution
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.StepID,
			&i.StepType,
			&i.Status,
			&i.Attempts,
			&i.InputJson,
			&i.OutputJson,
			&i.ErrorJson,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByEnvironment = `-- name: ListWorkflowsByEnvironment :many
SELECT id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at FROM workflows
WHERE environment_id = $1
	AND status <> 'archived'
ORDER BY updated_at DESC
`

func (q *Queries) ListWorkflowsByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Channels,
			&i.TemplateIds,
			&i.IsActive,
			&i.Status,
			&i.Version,
			&i.TriggerEvent,
			&i.DefinitionJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubscribers = `-- name: SearchSubscribers :many
SELECT id, environment_id, name, email, phone, push_token, channels, status, tags, preferences, subscription_date, last_notification_date, metadata, deleted_at, created_at, updated_at FROM subscribers
WHERE environment_id = $1 AND deleted_at IS NULL
  AND (LOWER(name) LIKE LOWER($2) OR LOWER(COALESCE(email, '')) LIKE LOWER($2))
ORDER BY subscription_date DESC
`

type SearchSubscribersParams struct {
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Lower         string    `db:"lower" json:"lower"`
}

func (q *Queries) SearchSubscribers(ctx context.Context, arg SearchSubscribersParams) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, searchSubscribers, arg.EnvironmentID, arg.Lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PushToken,
			&i.Channels,
			&i.Status,
			&i.Tags,
			&i.Preferences,
			&i.SubscriptionDate,
			&i.LastNotificationDate,
			&i.Metadata,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEnvironmentDefault = `-- name: SetEnvironmentDefault :exec
UPDATE environments
SET is_default = $2, updated_at = $3
WHERE id = $1
`

type SetEnvironmentDefaultParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	IsDefault bool               `db:"is_default" json:"is_default"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SetEnvironmentDefault(ctx context.Context, arg SetEnvironmentDefaultParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentDefault, arg.ID, arg.IsDefault, arg.UpdatedAt)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $1, updated_at = $2
WHERE id = $3
`

type TouchAPIKeyLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID         uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.LastUsedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateAPIKeyStatus = `-- name: UpdateAPIKeyStatus :exec
UPDATE api_keys
SET status = $1, revoked_at = $2, updated_at = $3
WHERE id = $4
`

type UpdateAPIKeyStatusParams struct {
	Status    string             `db:"status" json:"status"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID        uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateAPIKeyStatus(ctx context.Context, arg UpdateAPIKeyStatusParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyStatus,
		arg.Status,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateEnvironmentName = `-- name: UpdateEnvironmentName :exec
UPDATE environments
SET name = $2, updated_at = $3
WHERE id = $1
`

type UpdateEnvironmentNameParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateEnvironmentName(ctx context.Context, arg UpdateEnvironmentNameParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentName, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integrations
SET name = $3, channel = $4, credentials = $5, config = $6, updated_at = now()
WHERE id = $1 AND environment_id = $2
RETURNING id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
`

type UpdateIntegrationParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Channel       string    `db:"channel" json:"channel"`
	Credentials   []byte    `db:"credentials" json:"credentials"`
	Config        []byte    `db:"config" json:"config"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegration,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Channel,
		arg.Credentials,
		arg.Config,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Credentials,
		&i.Config,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIntegrationState = `-- name: UpdateIntegrationState :one
UPDATE integrations
SET is_active = $3, is_primary = $4, updated_at = now()
WHERE id = $1 AND environment_id = $2
RETURNING id, environment_id, name, channel, credentials, config, is_active, is_primary, created_at, updated_at
`

type UpdateIntegrationStateParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	IsActive      bool      `db:"is_active" json:"is_active"`
	IsPrimary     bool      `db:"is_primary" json:"is_primary"`
}

func (q *Queries) UpdateIntegrationState(ctx context.Context, arg UpdateIntegrationStateParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegrationState,
		arg.ID,
		arg.EnvironmentID,
		arg.IsActive,
		arg.IsPrimary,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Credentials,
		&i.Config,
		&i.IsActive,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET status = $1, updated_at = $2
WHERE id = $3
`

type UpdateNotificationStatusParams struct {
	Status    string             `db:"status" json:"status"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID        uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateOrganizationName = `-- name: UpdateOrganizationName :exec
UPDATE organizations
SET name = $2, updated_at = $3
WHERE id = $1
`

type UpdateOrganizationNameParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationName, arg.ID, arg.Name, arg.UpdatedAt)
	return err
}

const updateSubscriber = `-- name: UpdateSubscriber :one
UPDATE subscribers
SET name = $3,
	email = $4,
	phone = $5,
	push_token = $6,
	channels = $7,
	status = $8,
	tags = $9,
	metadata = $10,
	preferences = $11,
	updated_at = now()
WHERE id = $1 AND environment_id = $2 AND deleted_at IS NULL
RETURNING id, environment_id, name, email, phone, push_token, channels, status, tags, preferences, subscription_date, last_notification_date, metadata, deleted_at, created_at, updated_at
`

type UpdateSubscriberParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Email         *string   `db:"email" json:"email"`
	Phone         *string   `db:"phone" json:"phone"`
	PushToken     *string   `db:"push_token" json:"push_token"`
	Channels      []string  `db:"channels" json:"channels"`
	Status        []byte    `db:"status" json:"status"`
	Tags          []string  `db:"tags" json:"tags"`
	Metadata      []byte    `db:"metadata" json:"metadata"`
	Preferences   []byte    `db:"preferences" json:"preferences"`
}

func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, updateSubscriber,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PushToken,
		arg.Channels,
		arg.Status,
		arg.Tags,
		arg.Metadata,
		arg.Preferences,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PushToken,
		&i.Channels,
		&i.Status,
		&i.Tags,
		&i.Preferences,
		&i.SubscriptionDate,
		&i.LastNotificationDate,
		&i.Metadata,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET subject = $3, body = $4, version = version + 1, updated_at = now()
WHERE id = $1 AND environment_id = $2
RETURNING id, environment_id, name, channel, subject, body, version, is_active, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Subject       *string   `db:"subject" json:"subject"`
	Body          string    `db:"body" json:"body"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.EnvironmentID,
		arg.Subject,
		arg.Body,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmailVerifiedAt = `-- name: UpdateUserEmailVerifiedAt :exec
UPDATE users
SET email_verified_at = $2, updated_at = $3
WHERE id = $1
`

type UpdateUserEmailVerifiedAtParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserEmailVerifiedAt(ctx context.Context, arg UpdateUserEmailVerifiedAtParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerifiedAt, arg.ID, arg.EmailVerifiedAt, arg.UpdatedAt)
	return err
}

const updateUserOnboardingCompletedAt = `-- name: UpdateUserOnboardingCompletedAt :exec
UPDATE users
SET onboarding_completed_at = $2, updated_at = $3
WHERE id = $1
`

type UpdateUserOnboardingCompletedAtParams struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	OnboardingCompletedAt pgtype.Timestamptz `db:"onboarding_completed_at" json:"onboarding_completed_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserOnboardingCompletedAt(ctx context.Context, arg UpdateUserOnboardingCompletedAtParams) error {
	_, err := q.db.Exec(ctx, updateUserOnboardingCompletedAt, arg.ID, arg.OnboardingCompletedAt, arg.UpdatedAt)
	return err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET key = $3,
	name = $4,
	description = $5,
	channels = $6,
	template_ids = $7,
	is_active = $8,
	updated_at = now()
WHERE id = $1 AND environment_id = $2
RETURNING id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Key           string    `db:"key" json:"key"`
	Name          string    `db:"name" json:"name"`
	Description   *string   `db:"description" json:"description"`
	Channels      []string  `db:"channels" json:"channels"`
	TemplateIds   []byte    `db:"template_ids" json:"template_ids"`
	IsActive      bool      `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.EnvironmentID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Channels,
		arg.TemplateIds,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Channels,
		&i.TemplateIds,
		&i.IsActive,
		&i.Status,
		&i.Version,
		&i.TriggerEvent,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowDefinition = `-- name: UpdateWorkflowDefinition :one
UPDATE workflows
SET key = $3,
	name = $4,
	description = $5,
	status = $6,
	version = $7,
	trigger_event = $8,
	definition_json = $9,
	is_active = CASE WHEN $6 = 'active' THEN true ELSE false END,
	updated_at = now()
WHERE id = $1 AND environment_id = $2
RETURNING id, environment_id, key, name, description, channels, template_ids, is_active, status, version, trigger_event, definition_json, created_at, updated_at
`

type UpdateWorkflowDefinitionParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EnvironmentID  uuid.UUID `db:"environment_id" json:"environment_id"`
	Key            string    `db:"key" json:"key"`
	Name           string    `db:"name" json:"name"`
	Description    *string   `db:"description" json:"description"`
	Status         string    `db:"status" json:"status"`
	Version        int32     `db:"version" json:"version"`
	TriggerEvent   *string   `db:"trigger_event" json:"trigger_event"`
	DefinitionJson []byte    `db:"definition_json" json:"definition_json"`
}

func (q *Queries) UpdateWorkflowDefinition(ctx context.Context, arg UpdateWorkflowDefinitionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflowDefinition,
		arg.ID,
		arg.EnvironmentID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Version,
		arg.TriggerEvent,
		arg.DefinitionJson,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Channels,
		&i.TemplateIds,
		&i.IsActive,
		&i.Status,
		&i.Version,
		&i.TriggerEvent,
		&i.DefinitionJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowExecutionState = `-- name: UpdateWorkflowExecutionState :one
UPDATE workflow_executions
SET status = $3,
	current_step_id = $4,
	completed_at = $5,
	failed_at = $6,
	updated_at = now()
WHERE id = $1 AND environment_id = $2
RETURNING id, workflow_id, environment_id, subscriber_id, status, current_step_id, trigger_payload, started_at, completed_at, failed_at, created_at, updated_at
`

type UpdateWorkflowExecutionStateParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	EnvironmentID uuid.UUID          `db:"environment_id" json:"environment_id"`
	Status        string             `db:"status" json:"status"`
	CurrentStepID *string            `db:"current_step_id" json:"current_step_id"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	FailedAt      pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
}

func (q *Queries) UpdateWorkflowExecutionState(ctx context.Context, arg UpdateWorkflowExecutionStateParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, updateWorkflowExecutionState,
		arg.ID,
		arg.EnvironmentID,
		arg.Status,
		arg.CurrentStepID,
		arg.CompletedAt,
		arg.FailedAt,
	)
	var i WorkflowExecution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.EnvironmentID,
		&i.SubscriberID,
		&i.Status,
		&i.CurrentStepID,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowStepExecutionState = `-- name: UpdateWorkflowStepExecutionState :one
UPDATE workflow_step_executions
SET status = $3,
	attempts = $4,
	input_json = $5,
	output_json = $6,
	error_json = $7,
	started_at = $8,
	completed_at = $9,
	failed_at = $10,
	updated_at = now()
WHERE execution_id = $1 AND step_id = $2
RETURNING id, execution_id, step_id, step_type, status, attempts, input_json, output_json, error_json, started_at, completed_at, failed_at, created_at, updated_at
`

type UpdateWorkflowStepExecutionStateParams struct {
	ExecutionID uuid.UUID          `db:"execution_id" json:"execution_id"`
	StepID      string             `db:"step_id" json:"step_id"`
	Status      string             `db:"status" json:"status"`
	Attempts    int32              `db:"attempts" json:"attempts"`
	InputJson   []byte             `db:"input_json" json:"input_json"`
	OutputJson  []byte             `db:"output_json" json:"output_json"`
	ErrorJson   []byte             `db:"error_json" json:"error_json"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	FailedAt    pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
}

func (q *Queries) UpdateWorkflowStepExecutionState(ctx context.Context, arg UpdateWorkflowStepExecutionStateParams) (WorkflowStepExecution, error) {
	row := q.db.QueryRow(ctx, updateWorkflowStepExecutionState,
		arg.ExecutionID,
		arg.StepID,
		arg.Status,
		arg.Attempts,
		arg.InputJson,
		arg.OutputJson,
		arg.ErrorJson,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
	)
	var i WorkflowStepExecution
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.StepID,
		&i.StepType,
		&i.Status,
		&i.Attempts,
		&i.InputJson,
		&i.OutputJson,
		&i.ErrorJson,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmailVerification = `-- name: UpsertEmailVerification :exec
INSERT INTO email_verifications (
	user_id,
	code_hash,
	expires_at,
	consumed_at,
	created_at,
	updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE
SET code_hash = EXCLUDED.code_hash,
	expires_at = EXCLUDED.expires_at,
	consumed_at = EXCLUDED.consumed_at,
	updated_at = EXCLUDED.updated_at
`

type UpsertEmailVerificationParams struct {
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	CodeHash   string             `db:"code_hash" json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertEmailVerification(ctx context.Context, arg UpsertEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, upsertEmailVerification,
		arg.UserID,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.ConsumedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertNotificationByEnvironmentJob = `-- name: UpsertNotificationByEnvironmentJob :one
INSERT INTO notifications (id, job_id, environment_id, title, message, channels, recipient, metadata, status, is_test, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT (job_id) WHERE job_id IS NOT NULL DO UPDATE
SET title = EXCLUDED.title,
	message = EXCLUDED.message,
	channels = EXCLUDED.channels,
	recipient = EXCLUDED.recipient,
	metadata = EXCLUDED.metadata,
	status = EXCLUDED.status,
	updated_at = EXCLUDED.updated_at
RETURNING id, title, message, channels, recipient, metadata, status, environment_id, job_id, is_test, created_at, updated_at
`

type UpsertNotificationByEnvironmentJobParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	JobID         *string            `db:"job_id" json:"job_id"`
	EnvironmentID pgtype.UUID        `db:"environment_id" json:"environment_id"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	Channels      []string           `db:"channels" json:"channels"`
	Recipient     []byte             `db:"recipient" json:"recipient"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Status        string             `db:"status" json:"status"`
	IsTest        bool               `db:"is_test" json:"is_test"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UpsertNotificationByEnvironmentJobRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	Channels      []string           `db:"channels" json:"channels"`
	Recipient     []byte             `db:"recipient" json:"recipient"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	Status        string             `db:"status" json:"status"`
	EnvironmentID pgtype.UUID        `db:"environment_id" json:"environment_id"`
	JobID         *string            `db:"job_id" json:"job_id"`
	IsTest        bool               `db:"is_test" json:"is_test"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertNotificationByEnvironmentJob(ctx context.Context, arg UpsertNotificationByEnvironmentJobParams) (UpsertNotificationByEnvironmentJobRow, error) {
	row := q.db.QueryRow(ctx, upsertNotificationByEnvironmentJob,
		arg.ID,
		arg.JobID,
		arg.EnvironmentID,
		arg.Title,
		arg.Message,
		arg.Channels,
		arg.Recipient,
		arg.Metadata,
		arg.Status,
		arg.IsTest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UpsertNotificationByEnvironmentJobRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.Channels,
		&i.Recipient,
		&i.Metadata,
		&i.Status,
		&i.EnvironmentID,
		&i.JobID,
		&i.IsTest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTemplate = `-- name: UpsertTemplate :one
INSERT INTO templates (id, environment_id, name, channel, subject, body)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (environment_id, name, channel)
DO UPDATE SET subject = $5, body = $6, version = templates.version + 1, updated_at = NOW()
RETURNING id, environment_id, name, channel, subject, body, version, is_active, created_at, updated_at
`

type UpsertTemplateParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	EnvironmentID uuid.UUID `db:"environment_id" json:"environment_id"`
	Name          string    `db:"name" json:"name"`
	Channel       string    `db:"channel" json:"channel"`
	Subject       *string   `db:"subject" json:"subject"`
	Body          string    `db:"body" json:"body"`
}

func (q *Queries) UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, upsertTemplate,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.Channel,
		arg.Subject,
		arg.Body,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
