// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPushSubscriptions = `-- name: GetPushSubscriptions :many
SELECT id, user_id, channel, endpoint, created_at
FROM push_subscriptions
WHERE user_id = $1
`

func (q *Queries) GetPushSubscriptions(ctx context.Context, userID string) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Endpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByAPIKey = `-- name: GetServiceByAPIKey :one
SELECT id, name, api_key, description, created_at
FROM services
WHERE api_key = $1
`

func (q *Queries) GetServiceByAPIKey(ctx context.Context, apiKey string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByAPIKey, apiKey)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, email_opt_in, sms_opt_in
FROM users_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UsersPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UsersPreference
	err := row.Scan(&i.UserID, &i.EmailOptIn, &i.SmsOptIn)
	return i, err
}

const insertInAppNotification = `-- name: InsertInAppNotification :exec
INSERT INTO in_app_notifications (id, user_id, title, message, metadata, created_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertInAppNotificationParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Title     string             `db:"title" json:"title"`
	Message   string             `db:"message" json:"message"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertInAppNotification(ctx context.Context, arg InsertInAppNotificationParams) error {
	_, err := q.db.Exec(ctx, insertInAppNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (id, service_id, user_id, title, message, channels, metadata, status, retry_count, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type InsertNotificationParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ServiceID  uuid.UUID          `db:"service_id" json:"service_id"`
	UserID     string             `db:"user_id" json:"user_id"`
	Title      string             `db:"title" json:"title"`
	Message    string             `db:"message" json:"message"`
	Channels   []string           `db:"channels" json:"channels"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	Status     string             `db:"status" json:"status"`
	RetryCount int32              `db:"retry_count" json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.ServiceID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Channels,
		arg.Metadata,
		arg.Status,
		arg.RetryCount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertInAppNotification = `-- name: UpsertInAppNotification :exec
INSERT INTO in_app_notifications (id, user_id, title, message, metadata, created_at) VALUES ($1,$2,$3,$4,$5,$6)
`

type UpsertInAppNotificationParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Title     string             `db:"title" json:"title"`
	Message   string             `db:"message" json:"message"`
	Metadata  []byte             `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertInAppNotification(ctx context.Context, arg UpsertInAppNotificationParams) error {
	_, err := q.db.Exec(ctx, upsertInAppNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}
